### PR TITLE
Switch to a Clojure-Ring style middleware (v0.1 proposal)

### PR DESCRIPTION
**Pull request by ntdef**
See [this article](http://drtom.ch/posts/2012-12-10/An_Introduction_to_Webprogramming_in_Clojure_-_Ring_and_Middleware/)

### CODE REVIEW

**Comment by IainNZ** [comment]
From #12 

> Given that this project has been abandoned, I'd like to take a stab at reviving it. I've been looking at some of the ways that Ring implements Middleware in Clojure, and I think it would be a good fit for some of the Julia functional idiosyncrasies. Pardon me if this was not the right venue, but I would like to request commit access to this repo, @malmaud (or whoever I need to request from).

**Comment by IainNZ** [comment]
@ntdef just skimming this PR, it looks like pretty much a complete re-write. Thats great, but I don't think it should replace what is in Meddle - instead, it should be a new package of its own, with a different name. Maybe you can then post your efforts to the community and if people like it, you could register it.

**Comment by ntdef** [comment]
I don't mind maintaining what's already here in principle. I just thought that using closures might make more sense than modifying the state of the Request object as it was passed along. Let's close this PR for now, and I'll work on adding some more tests and adding support for Julia 0.5.

**Comment by IainNZ** [comment]
I think your new design might make a lot of sense, I don't know really anything about this package or how it works internally. I'd really encourage you just to work on your own new package.

I don't understand what you mean about the branches.

**Pull request closed without merging**
